### ISSUE TITLE
get the ArrayList of Centres of a certain type

### ISSUE THREAD

**Issue by Asakar** [jamiehammond/sparta-simulator#77] opened 2021-01-07 11:27 UTC
DOD:
The number of centres of a specific type is returned as a ArrayList<Centre> .

Testing:

1: The number of centres of a specific type that are in the centres list should match with the number of centres in the array list returned by the method.

Dificulty: Moderate

DEV
-------------------------------------------
public ArrayList<Centre> getCentresByCentreType(CentreType){}

**Comment by Samurahh** [comment] 2021-01-07 18:05
Duplicate of #79

**Closed by Samurahh** 2021-01-07 18:05 UTC
Labels: duplicate
